# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all
org.gradle.configuration-cache=false

## gradle versions
jmh_version=0.7.3

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-5
min_minecraft_version=26.1-alpha.5
yarn_mappings=26.1-snapshot-5+build.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.11
maven_group=org.codeberg.zenxarch.fastnoise
archives_base_name=zfastnoise

# Dependencies
minotaur_version=2.+