# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
min_minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.4
loom_version=1.15.3

# Mod Properties
mod_version=1.0.19
maven_group=org.codeberg.zenxarch.fastnoise
archives_base_name=zfastnoise

# Dependencies
night_config_version=3.8.3

# Plugins
minotaur_version=2.+
jmh_version=0.7.3