# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-10
min_minecraft_version=26.1-alpha.10
yarn_mappings=26.1-snapshot-10+build.1
yarn_mappings_patch=26.1+build.1
loom_version=1.15.15

minecraft_version_range=[26.1-snapshot-10]
neo_version=26.1.0.0-alpha.13+snapshot-10

# Mod Properties
mod_version=1.0.20
maven_group=org.codeberg.zenxarch.fastnoise
archives_base_name=zfastnoise

# Dependencies
mixinextras_version=0.5.0

# Plugins
minotaur_version=2.+
jmh_version=0.7.3
